name: Auto Assign

on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign reviewers'
        uses: kentaro-m/auto-assign-action@v1.2.2
        with:
          reviewers: 'Reno594, miusuario1, miusuario2'
          team-reviewers: 'myteam'
