name: Issue assignment

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1.11.0
        with:
          assignees: Reno594, miusuario1, miusuario2, miusuario3, miusuario4
          numOfAssignee: 1

